title: Jacob Pederson's Portfolio
description: > # this means to ignore newlines until "baseurl:"
  I am a level designer who's passionate about games and creating worlds from my mind.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jacob Pederson # add your name
author-img: Jacob-Pederson.jpg # add your photo
about-author: I am a level designer who's passionate about games and creating worlds from my mind. # add description
social-twitter: @krimzonko # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: avernus-jcp # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: pedersonjacob17@gmail.com# add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
